package ro.project.enums;

public enum Intrebare {
    CHIAR_SI_IN_TIMPUL_LIBER_MA_GANDESC_LA_O_MULŢIME_DE_PROBLEME(1),
    IMI_PLACE_SA_MI_ORGANIZEZ_FIECARE_LUCRU_PE_CARE_L_INCEP(2),
    IN_TRECUT_ERAM_ORGANIZATORUL_UNUI_GRUP_DE_PRIETENI_A_UNUI_CLUB(3),
    PENTRU_A_CERCETA_LUCRURILE_IN_PROFUNZIME_INCERC_SA_NU_IAU_IN_SEAMA_APARENTELE(4),
    CAUT_SA_FIU_PREGATIT_PENTRU_ORICE_SOLICITARE(5),
    MA_SIMT_IN_FORMA_CEA_MAI_BUNA(6),
    IN_REZOLVAREA_UNOR_PROBLEME_CAUT_SA_AFLU_SOLUTIA_CEA_MAI_BUNA(7),
    MI_SE_PARE_DESTUL_DE_IMPORTANT_SA_MI_SE_SPUNA_CE_SE_ASTEAPTA_DE_LA_MINE(8),
    CAUT_SA_MI_REZOLV_CAT_MAI_REPEDE_SARCINILE_DE_LUCRU(9),
    MA_PROVOACA_IDEEA_DE_A_LUA_PARTE_LA_O_CERCETARE_STIINTIFICA(10),
    UN_LOC_DE_MUNCA_CE_MI_PERMITE_SA_IAU_DECIZII_MI_SE_POTRIVESTE_CEL_MAI_MULT(11),
    LA_REZOLVAREA_UNOR_PROBLEME_AM_TENDINTA_SA_DESPIC_FIRUL_IN_PATRU_PANA_CAND_GASESC_SOLUTIA_CEA_MAI_BUNA(12),
    DECAT_SA_MA_PLIMB_PRINTR_UN_PARC_PREFER_SA_CITESC_UN_STUDIU_DEDICAT_GRIPEI_AVIARE(13),
    MI_SE_PARE_NORMAL_SA_MA_CONFORMEZ_UNOR_REGULI_DE_MUNCA(14),
    DIN_CATE_MA_CUNOSC_CRED_CA_AS_PUTEA_SA_FIU_UN_SEF_DE_SUCCES(15),
    IMI_PLACE_SA_REZOLV_UN_LUCRU_CARE_PE_ALTII_II_PLICTISESTE(16),
    PRIN_FELUL_MEU_DE_A_FI_IMI_PLACE_SA_AM_MULTE_RESPONSABILITATI(17),
    CAND_IMI_REVINE_REZOLVAREA_UNEI_PROBLEME_IMI_TREC_PRIN_MINTE_TOT_FELUL_DE_IDEI(18),
    DISCIPLINA_LA_UN_LOC_DE_MUNCA_MI_SE_PARE_DEOSEBIT_DE_IMPORTANTA(19),
    MA_PROVOACA_IDEEA_SA_FIU_SEF(20),
    DACA_CER_CEVA_CUIVA_SUNT_ATENT_SA_VAD_CE_INTENTII_ARE(21),
    PREFER_SA_NU_PRIMESC_O_ALTA_LUCRARE_PANA_NU_DUC_LA_BUN_SFARSIT_CEEA_CE_AM_INCEPUT(22),
    IMI_ASUM_ESECUL_PENTRU_ORICE_LUCRU_PE_CARE_IL_REALIZEZ(23),
    INTR_O_ACTIVITATE_COLECTIVA_IMI_PLACE_SA_I_SPUN_FIECARUIA_CE_ARE_DE_FACUT(24);

    public final int label;

    private Intrebare(int label) {
        this.label = label;
    }
}
