BEGIN;
INSERT INTO intrebare(nume) VALUES('Chiar şi în timpul liber, mă gândesc la o mulţime de probleme.');
INSERT INTO intrebare(nume) VALUES('Îmi place să-mi organizez fiecare lucru pe care-l încep.');
INSERT INTO intrebare(nume) VALUES('În trecut eram organizatorul unui grup de prieteni, a unui club etc.');
INSERT INTO intrebare(nume) VALUES('Pentru a cerceta lucrurile în profunzime, încerc să nu iau în seamă aparenţele.');
INSERT INTO intrebare(nume) VALUES('Caut să fiu pregătit pentru orice solicitare.');
INSERT INTO intrebare(nume) VALUES('Mă simt în forma cea mai bună.');
INSERT INTO intrebare(nume) VALUES('În rezolvarea unor probleme, caut să aflu soluţia cea mai bună.');
INSERT INTO intrebare(nume) VALUES('Mi se pare destul de important să mi se spună ce se aşteaptă de la mine.');
INSERT INTO intrebare(nume) VALUES('Caut să-mi rezolv cât mai repede sarcinile de lucru.');
INSERT INTO intrebare(nume) VALUES('Mă provoacă ideea de a lua parte la o cercetare ştiinţifică.');
INSERT INTO intrebare(nume) VALUES('Un loc de muncă ce-mi permite să iau decizii mi se potriveşte cel mai mult.');
INSERT INTO intrebare(nume) VALUES('La rezolvarea unor probleme am tendinţa să despic firul în patru până când găsesc soluţia cea mai bună.');
INSERT INTO intrebare(nume) VALUES('Decât să mă plimb printr-un parc, prefer să citesc un studiu dedicat gripei aviare.');
INSERT INTO intrebare(nume) VALUES('Mi se pare normal să mă conformez unor reguli de muncă.');
INSERT INTO intrebare(nume) VALUES('Din câte mă cunosc, cred că aş putea să fiu un şef de succes.');
INSERT INTO intrebare(nume) VALUES('Îmi place să rezolv un lucru care pe alţii îi plictiseşte.');
INSERT INTO intrebare(nume) VALUES('Prin felul meu de a fi, îmi place să am multe responsabilităţi.');
INSERT INTO intrebare(nume) VALUES('Când îmi revine rezolvarea unei probleme, îmi trec prin minte tot felul de idei.');
INSERT INTO intrebare(nume) VALUES('Disciplina la un loc de muncă mi se pare deosebit de importantă.');
INSERT INTO intrebare(nume) VALUES('Mă provoacă ideea să fiu şef.');
INSERT INTO intrebare(nume) VALUES('Dacă cer ceva cuiva, sunt atent să văd ce intenţii are.');
INSERT INTO intrebare(nume) VALUES('Prefer să nu primesc o altă lucrare, până nu duc la bun sfârşit ceea ce am început.');
INSERT INTO intrebare(nume) VALUES('Îmi asum eşecul pentru orice lucru pe care îl realizez.');
INSERT INTO intrebare(nume) VALUES('Într-o activitate colectivă, îmi place să-i spun fiecăruia ce are de făcut.');
COMMIT;